server:
  port: 8090

spring:
  application:
    name: gateway


#  cloud:
#    gateway:
#      routes:
#        - id: gateway-route
#          uri: lb://client1
#          predicates:
#            - Path=/client/**
#
#        - id: gateway-route2
#          uri: lb://client2
#          predicates:
#            - Path=/client2/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
